name: send-weather-CheckIn
on:
  push:
    branches: [ main ]
    paths-ignore: 
      - 'README.md'
  schedule:
    - cron: 30 1 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install axios
        run: npm install axios
      - name: install urlencode
        run: npm install urlencode
      - name: CheckIn
        run: node checkin.js
        env:
          SCKEY: ${{ secrets.SCKEY }}
